version: 2.1

jobs:
  build-and-test:
    steps:
      - run:
          name: Install dependencies
          command: |
            pip install --user -r requirements.txt
      - run:
          name: Test
          command: |
            python manage.py test

workflows:
  main:
    jobs:
      - build-and-test
