version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - setup_remote_docker:
        version: 19.03.13
      - run:
          name: Install dependencies
          command: |
            pip install --user -r requirements.txt
      - run:
          name: Test
          command: |
            python manage.py test
      - run:
          name: Build docker image on test passed
          command: |
            docker build -t todolist-app .

workflows:
  main:
    jobs:
      - build-and-test
