# Generated by Django 3.1.3 on 2020-11-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20201103_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='list_id',
            field=models.IntegerField(),
        ),
    ]
