# Generated by Django 3.1.3 on 2020-11-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_auto_20201102_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
